import { SoundDefinition } from '../types'

// Bundled sounds ship in public/sounds/ — run `pnpm download-sounds` to fetch them.
// Non-bundled sounds are lazy-downloaded from Freesound/Pixabay on first add.
export const BUILT_IN_SOUNDS: SoundDefinition[] = [
  {
    id: 'rain',
    name: 'Rain',
    icon: 'CloudRain',
    color: '#1a3a5c',
    iconColor: '#4da6ff',
    tag: 'weather',
    freesoundId: 531871,
    pixabayQuery: 'rain',
    bundled: true,
  },
  {
    id: 'birds',
    name: 'Birds',
    icon: 'Feather',
    color: '#1a3a28',
    iconColor: '#4ade80',
    tag: 'nature',
    freesoundId: 800712,
    pixabayQuery: 'birds chirping',
    bundled: true,
  },
  {
    id: 'ocean',
    name: 'Ocean Waves',
    icon: 'Waves',
    color: '#0f2a35',
    iconColor: '#38bdf8',
    tag: 'nature',
    freesoundId: 157881,
    pixabayQuery: 'ocean waves',
    bundled: true,
  },
  {
    id: 'forest',
    name: 'Forest',
    icon: 'Trees',
    color: '#1a2e1a',
    iconColor: '#86efac',
    tag: 'nature',
    freesoundId: 405133,
    pixabayQuery: 'forest nature ambience',
    bundled: true,
  },
  {
    id: 'fire',
    name: 'Fireplace',
    icon: 'Flame',
    color: '#3a1a1a',
    iconColor: '#f97316',
    tag: 'indoor',
    freesoundId: 729395,
    pixabayQuery: 'fireplace crackling',
    bundled: true,
  },
  {
    id: 'cafe',
    name: 'Café',
    icon: 'Coffee',
    color: '#2a1e10',
    iconColor: '#d4a76a',
    tag: 'indoor',
    freesoundId: 453074,
    pixabayQuery: 'cafe coffee shop ambience',
    bundled: true,
  },
  {
    id: 'wind',
    name: 'Wind',
    icon: 'Wind',
    color: '#2a2a1a',
    iconColor: '#fbbf24',
    tag: 'weather',
    freesoundId: 175513,
    pixabayQuery: 'wind blowing',
    bundled: true,
  },
  {
    id: 'fan',
    name: 'Fan',
    icon: 'Fan',
    color: '#252525',
    iconColor: '#aaaaaa',
    tag: 'indoor',
    freesoundId: 618185,
    pixabayQuery: 'electric fan white noise',
    bundled: true,
  },
  {
    id: 'keyboard',
    name: 'Keyboard',
    icon: 'Keyboard',
    color: '#1a1a2e',
    iconColor: '#818cf8',
    tag: 'indoor',
    freesoundId: 361639,
    pixabayQuery: 'keyboard typing',
    bundled: true,
  },
  {
    id: 'night',
    name: 'Night Bugs',
    icon: 'Moon',
    color: '#0f1a2a',
    iconColor: '#c4b5fd',
    tag: 'nature',
    freesoundId: 648470,
    pixabayQuery: 'crickets night insects',
    bundled: true,
  },
  // ── Lazy-download only ───────────────────────────────────────────────────
  {
    id: 'thunder',
    name: 'Thunder',
    icon: 'Zap',
    color: '#2a1a4a',
    iconColor: '#a78bfa',
    tag: 'weather',
    freesoundId: 103953,
    pixabayQuery: 'thunder storm',
  },
  {
    id: 'crowd',
    name: 'Crowd',
    icon: 'Users',
    color: '#2a1a2a',
    iconColor: '#e879f9',
    tag: 'indoor',
    freesoundId: 522426,
    pixabayQuery: 'crowd chatter people',
  },
  {
    id: 'creek',
    name: 'Creek',
    icon: 'Droplets',
    color: '#0f2a2a',
    iconColor: '#67e8f9',
    tag: 'nature',
    freesoundId: 459827,
    pixabayQuery: 'creek stream water',
  },
  {
    id: 'train',
    name: 'Train',
    icon: 'Train',
    color: '#1e1e2a',
    iconColor: '#94a3b8',
    tag: 'travel',
    freesoundId: 371277,
    pixabayQuery: 'train riding ambient',
  },
]

export const BUNDLED_SOUNDS = BUILT_IN_SOUNDS.filter((s) => s.bundled)
